
//  Each new term in the Fibonacci sequence is generated by adding the previous two terms.
//  By starting with 1 and 2, the first 10 terms will be:
//        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//  By considering the terms in the Fibonacci sequence whose values do not exceed four million,
//  find the sum of the even-valued terms.

public class fibonacci {

    public static void main(String[] args) {

        int sum = 2;    // Starts with 1, 2: So 2 is added
        int n1=1;
        int n2=2;
        int n=0;

        while(n<4000000){
            n=n1+n2;
            n1=n2;
            n2=n;
            if(n%2==0){
                sum=sum+n;
            }
        }

        System.out.println("Sum: "+sum);
    }
}
